#!/bin/sh
# Stamp the build with a firmware version string derived from git.
#
# Invoked as a SEGGER Embedded Studio pre-build command, so it runs identically
# from the IDE, from `make bootloader netcore`, and from `make docker` - emBuild
# is the same build engine the IDE uses.
#
#   scripts/gen-version.sh <output-header-path>
#
# Two properties this script must have, both load-bearing:
#
#   1. It writes the header ONLY when the content changes. An unconditional
#      write touches the mtime on every build and forces a full rebuild of
#      everything that includes it.
#   2. It never fails. No git, a tarball export with no .git, or a CI image
#      without git installed must all still produce a compilable header. The
#      committed version.h wrapper falls back to "unknown" if this file is
#      missing entirely, so a failure here is never fatal either way.
#
# Resolve the repo from the script's own location rather than the caller's
# working directory, which differs between the IDE and make.

set -u

out="${1:-}"
if [ -z "$out" ]; then
    echo "gen-version.sh: no output path given" >&2
    exit 0
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(dirname -- "$script_dir")

version=$(git -C "$repo_dir" describe --always --dirty --tags 2>/dev/null) || version=""
[ -n "$version" ] || version="unknown"

new="/* Generated by scripts/gen-version.sh - do not edit, do not commit. */
#ifndef __VERSION_GENERATED_H
#define __VERSION_GENERATED_H

#define SWRMT_FW_VERSION \"$version\"

#endif
"

# Only write when the content actually differs, so an unchanged HEAD does not
# invalidate every object file that includes the header. Both sides go through
# command substitution: it strips trailing newlines, and comparing a stripped
# file against an unstripped string never matches.
if [ -f "$out" ]; then
    old=$(cat -- "$out" 2>/dev/null || printf '')
    if [ "$old" = "$(printf '%s' "$new")" ]; then
        exit 0
    fi
fi

mkdir -p -- "$(dirname -- "$out")" 2>/dev/null || exit 0
printf '%s' "$new" > "$out" 2>/dev/null || exit 0

echo "gen-version.sh: SWRMT_FW_VERSION=\"$version\" -> $out"
exit 0
